### ISSUE TITLE
provide asciinema/gif demo

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#109]

**Comment by lachmanfrantisek** [comment]
What about something like this:

![conu](https://user-images.githubusercontent.com/20214043/36303151-6708b64a-130b-11e8-995d-251aac406f92.gif)

We can use [scenario from devconf workshop](https://github.com/phracek/devconf2018-workshop/blob/master/conu.md). This is just an example.

Any suggestions?
