### ISSUE TITLE
Should `run` be method of Image?

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/conu#11]
I think `run` should be method or `Image` rather than container. When executing `docker run`, image is passed as an argument and a container is created. Similarly in our code, we should have `container = image.run()`.

Does this make sense?

**Comment by TomasTomecek** [comment]
docker-py supports your argument:

```
In [6]: c = docker.DockerClient()

In [7]: c.containers.run?

In [8]: c.containers.run
Out[8]: <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f3251b619b0>>
```

**Comment by praiskup** [comment]
If this is docker-only related, and we don't plan to support other alternative container technologies -- I have no huge preference.

Just a note -- there's nothing similar to image in systemd-nspawn, so there's won't be anything like Image.run().  So to me the ContainerFactory is a bit more generic approach;  also it seems to be more natural --> you run/start/stop a container, you don't run "image".

**Comment by bkabrda** [comment]
@praiskup thanks for the comment, that's a very good point. Another possibility is making `run` a class method of `Container`, hence we'd have `Container.run(<arguments>)`.

**Comment by praiskup** [comment]
Previously I thought there's `ContainerFactory`, not `Container` class.  My bad.

I'm always unsure whether class methods are good thing or rather workaround (at least if the class meant to be instantiated like here), 'cause the alternative is to cut the static code out into separate class.  But yeah, `Container.run()` would be (static) factory method, so +1.

**Comment by jscotka** [comment]
Othervise in docker, there is command: docker container run, not docker image run. So i prefer to have it in container from that reason

**Comment by TomasTomecek** [comment]
...and it accepts an image:

```
$ docker container run [OPTIONS] IMAGE
```

**Comment by TomasTomecek** [comment]
we discussed this and concluded that proposed workflow from Slavek makes perfect sense and makes things easier:
```
image = DockerImage("fedora")
container = image.run_via_binary(["ls", "-lha", "/"])
