### ISSUE TITLE
exc when cleaning tmpdir

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#117]
```
Exception ignored in: <bound method Backend.__del__ of <conu.backend.docker.backend.DockerBackend object at 0x7f45d3e30518>>
Traceback (most recent call last):
  File "conu/apidefs/backend.py", line 93, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by TomasTomecek** [comment]
I vote for providing backend as a context manager since `__del__` just doesn't work: I'm getting really weird exceptions when it seems like that plenty of imported modules are already deinitialized

**Comment by dhodovsk** [comment]
If it is a way to solve this issue, I'm also okay with that. Providing backend as context manager could also be used for cleaning up test artifacts - in cases developer doesn't want otherwise (cases when they want to debug failed tests, print container logs,...).
