### ISSUE TITLE
let `run_via_binary` accept command as a list of strings

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#143]
How about if `.run_via_binary` accepted the command to run in the container. Something like:

```python
def run_via_binary(self, command):
  if isinstance(command, list):
    b = DockerRunBuilder(command)
  elif isinstance(command, DockerRunBuilder):
    ...
  else:
    raise Nope()
```

**Comment by dhodovsk** [comment]
+1, It might be convenient to create DockerRunBuilder within run_via_binary. Would this relate also to additional_options?

**Comment by TomasTomecek** [comment]
That is a good point: I don't know. Definitely sounds convenient.
