### ISSUE TITLE
[RFE] provide a functionality for testing S2I images

### ISSUE THREAD

**Issue by dhodovsk** [fedora-modularity/conu#2]
_From @phracek on September 7, 2017 10:49_

When testing the s2i (source-to-image) support 
- [x] I just pass an image name, applications repo or path (both needs to be supported) and run command (sometimes additional options are needed)
- [x] the framework will run the `s2i build`
- [x] will check that the s2i usage works, etc …

_Copied from original issue: fedora-modularity/meta-test-family#90_

**Comment by dhodovsk** [comment]
_From @phracek on September 7, 2017 10:50_

@hhorak @praiskup Please provide more info what kind of other checks could be useful for you.

**Comment by dhodovsk** [comment]
_From @praiskup on September 7, 2017 11:8_

-1, specifying the needs here doesn't make sense.  For me it is much, much cheaper to actually go and write the library myself.  That's the point, please -- write the "real-life" tests and write a lib which helps you with this (not the other way around).

I would suggest you to have a look at any s2i/non-s2i image testing script, and rewrite some of them (e.g. postgrsql).  If you are able to write that testsuite with smaller line-count, you have a good library for testing images.

**Comment by dhodovsk** [comment]
_From @praiskup on September 7, 2017 11:15_

More concretely, we have the `$TEST_LIST` in [1].  Having a look at that, it should be 100% clear what abstraction/checks/asserts are needed.  Let me know if you want some more examples.

 https://github.com/sclorg/postgresql-container/blob/0b630e19ef99cc3af50cc9f22866d05cdf497e3e/hack/run_test

**Comment by dhodovsk** [comment]
_From @praiskup on September 7, 2017 12:22_

Also, you don't have to replace complete testsuite -> we can calmly have two testsuites in each image repository in parallel (hooked into `make test` target).  So, let's start with the most trivial test-cases.  Plus, any new useful testcase is very appreciated! 👍

**Comment by dhodovsk** [comment]
_From @phracek on September 13, 2017 7:12_

For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by jscotka** [comment]
This issue is little bit confusing when moved to this CONU project,
Has to be reworked because just containers are tested, and CONU should not care how artifacts are built.
We have to find just important, but still general functions what are usefull for S2I container testing (eg. Like S2I layout, some providing functions if any)
