### ISSUE TITLE
[RFE] MTF API requirements: provide a function for running SQL commands for a specific handle

### ISSUE THREAD

**Issue by dhodovsk** [fedora-modularity/conu#3]
_From @phracek on September 7, 2017 10:28_

MTF should be able to specify function for running SQL commands for a specific handle, which in real runs a separate container (ideally re-using the same instance for more commands), and checks output.. but the point is to have ability to specify such function in the component library

_Copied from original issue: fedora-modularity/meta-test-family#88_

**Comment by dhodovsk** [comment]
_From @phracek on September 13, 2017 7:12_

For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by jscotka** [comment]
CONU could provide some generic SQL class ihnerited from base Container class if anyone is interested? Are there some costumers for this? if there are nobody, then this should be low prio.

**Comment by TomasTomecek** [comment]
+1 for low prio, this seems to be too complicated
