### ISSUE TITLE
provide `make check` target

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#38]
@praiskup says it's a standard for make users, so let's do:

```
check: test
```

since we need `make test` for our CI

**Comment by praiskup** [comment]
Not only that `make check` is in GNU/Linux standard make target (coding standards), but `test` is also not semantically correct (but this is not too serious comment from me!), per: http://www.developsense.com/blog/2009/08/testing-vs-checking/

**Comment by TomasTomecek** [comment]
https://github.com/fedora-modularity/conu/blob/master/Makefile#L15
