### ISSUE TITLE
[RFE] MTF API library: function for checking specific container issues

### ISSUE THREAD

**Issue by dhodovsk** [fedora-modularity/conu#4]
_From @phracek on September 7, 2017 10:10_

MTF has to provide a API library with function which will check these container issues:

- [x] support whether daemon serves content on specific port - done in https://github.com/fedora-modularity/conu/commit/763eafb52d537c8c3798add8b787323bbe92e56d
- [x] checking whether response returns 200 - done in https://github.com/fedora-modularity/conu/commit/9428f4dcdd8a88ff7d4eb1bc343ab370fed6c114
- [x] add support for specific combination of container parameters which should not work - done in https://github.com/fedora-modularity/conu/commit/d1b66c04b5b0f5ad6453d0944b725dff038b2a4f
- [x] function for check if specific file exists inside container  - done in https://github.com/fedora-modularity/conu/commit/3d8f08a88dd9bea3c753dc3933dd09871e957e15
- [x] function for check rpm signarures - tracked in https://github.com/fedora-modularity/conu/issues/75
- [ ] function for check help page and things which are important
- [ ] create a document under api http://meta-test-family.readthedocs.io/en/latest/api/index.html which will provide list and description. I would prefer to name it like API.

Think about to create new modules in folder like moduleframework/api/

_Copied from original issue: fedora-modularity/meta-test-family#86_

**Comment by dhodovsk** [comment]
_From @phracek on September 13, 2017 7:11_

For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by jscotka** [comment]
Partially done via `conu.utils` module.

and second part is move here library `dockerlinter` : https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/dockerlinter.py and also
some classes from `module lint`. But we have to ensure to place it to proper module, for example check rpm signatures is nothig specific to docker. it is also relevant for normal system too or also checking if file exist (BTW it is implemented but for host to test interaction https://github.com/fedora-modularity/conu/blob/master/conu/utils/core.py#L108)

**Comment by TomasTomecek** [comment]
each of the item in the original post should be a separate PR/issue.

**Comment by dhodovsk** [comment]
@phracek could you please add an update for the last two points? I believe they are already done or related to MTF

**Comment by phracek** [comment]
From my point of view, the last point regards to MTF directly. I have to think about it, because it is totally missing. We should provide some API document on RTD.
@jscotka What do you think about last point?

**Comment by TomasTomecek** [comment]
I think we can close this issue since the unresolved points are either tracked in separate issues or are irrelevant.
