### ISSUE TITLE
let's disable travis in favor of superCI

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#45]
Since conu uses atomic and travis is using ubuntu and aufs, we really need to test conu on Fedora.

Therefore I propose to disable travis - superCI is finally working and installing deps before running the tests.

Thoughts? @dhodovsk @bkabrda

**Comment by praiskup** [comment]
SuperCI is alternative to travis? (just curious, if yes -> I'd like to use that)

**Comment by TomasTomecek** [comment]
superCI is our internal jenkins instance set up by @psklenar and @jscotka :D

**Comment by bkabrda** [comment]
No objections on my side.

**Comment by dhodovsk** [comment]
No objections on my side either.

**Comment by TomasTomecek** [comment]
done
