### ISSUE TITLE
Readme needs some love

### ISSUE THREAD

**Issue by eliskasl** [fedora-modularity/conu#60]
Links in the readme don't work and some better usage overview in general would come in handy anyway.
Since we have http://conu.readthedocs.io/en/latest/, it should be linked from the readme as well.

Edit, Tomas: I would like to propose this AC:
- [x] punchline -- conu in one sentence
- [x] detailed list of features
- [x] showcase -- simple test, or just a usage -- ideally an existing example
- [x] installation
- [x] link to docs

**Comment by TomasTomecek** [comment]
should be fixed in master, and even more improved in #91
